### ISSUE TITLE
Prepare 2.0 release

### ISSUE THREAD

**Issue by jaimergp** [conda/menuinst#158]
### Summary

Placeholder for `menuinst 2.0.x` release.

| Pilot | @jaimergp |
|---|---|
| Co-pilot | N/A |

### Tasks

[milestone]: https://github.com/conda/menuinst/milestone/2
[process]: https://github.com/conda/conda/blob/main/RELEASE.md
[releases]: https://github.com/conda/menuinst/releases
[main]: https://github.com/AnacondaRecipes/menuinst-feedstock
[conda-forge]: https://github.com/conda-forge/menuinst-feedstock

#### The week before release week

- [x] Ensure release candidates are being successfully built (see `conda-canary/label/dev`)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    

#### Release week

- [x] Create release PR (see [release process][process]): https://github.com/conda/menuinst/pull/159
- [x] [Publish release][releases]
- [x] Feedstocks
    - [x] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock][main] - https://github.com/AnacondaRecipes/menuinst-feedstock/pull/7
    - [X] Bump version & update dependencies/tests in [conda-forge feedstock][conda-forge]:
      - [X] https://github.com/conda-forge/menuinst-feedstock/pull/23
      - [X] https://github.com/conda-forge/menuinst-feedstock/pull/26
      - [X] https://github.com/conda-forge/menuinst-feedstock/pull/25
    
- [X] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [ ] conda.org (link to pull request)
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

**Comment by jaimergp** [comment]
2.0 has been out for a bit :)
